In [1]:
import pandas as pd
from scipy.stats import ttest_1samp

In [12]:
sample = [2, 3, 4, 5, 6, 7, 8, 9, 10]
population_mean = 0

t_statistic, p_value = ttest_1samp(sample, population_mean)


In [10]:
t_statistic

1.0954451150103321

In [11]:
p_value

0.3052013652062302

In [2]:

# import data
df = pd.read_csv('quarterly_returns.csv')

# 数据预处理：确保年份为整数
df['年份'] = df['年份'].astype(int)

# 过滤出2014到2023年的数据
df_filtered = df[(df['年份'] >= 2014) & (df['年份'] <= 2023)]

# 查看 DataFrame 中每列的数据类型
print(df_filtered.dtypes)


年份         int64
分组         int64
季度         int64
加权回报率    float64
月份        object
dtype: object


In [17]:
df_filtered

年份  分组  季度     加权回报率    月份
165  2014   0   4  0.003441   1-4
166  2014   0   8  0.150171   5-8
167  2014   0  12  0.334022  9-12
168  2014   1   4  0.046654   1-4
169  2014   1   8  0.161585   5-8
..    ...  ..  ..       ...   ...
310  2023   3   8 -0.011386   5-8
311  2023   3  12 -0.044700  9-12
312  2023   4   4  0.113041   1-4
313  2023   4   8  0.027757   5-8
314  2023   4  12 -0.077884  9-12

[150 rows x 5 columns]

In [16]:
group1_df = df_filtered.loc[(df_filtered['分组'] == 0)] 

group1_df

年份  分组  季度     加权回报率    月份
165  2014   0   4  0.003441   1-4
166  2014   0   8  0.150171   5-8
167  2014   0  12  0.334022  9-12
180  2015   0   4  0.428129   1-4
181  2015   0   8  0.081184   5-8
182  2015   0  12  0.119136  9-12
195  2016   0   4 -0.168936   1-4
196  2016   0   8  0.029741   5-8
197  2016   0  12  0.151598  9-12
210  2017   0   4  0.007260   1-4
211  2017   0   8 -0.020618   5-8
212  2017   0  12  0.076634  9-12
225  2018   0   4 -0.014359   1-4
226  2018   0   8 -0.142111   5-8
227  2018   0  12 -0.079545  9-12
240  2019   0   4  0.408706   1-4
241  2019   0   8 -0.066169   5-8
242  2019   0  12  0.016893  9-12
255  2020   0   4  0.004066   1-4
256  2020   0   8  0.378518   5-8
257  2020   0  12 -0.012022  9-12
270  2021   0   4  0.008803   1-4
271  2021   0   8  0.260053   5-8
272  2021   0  12  0.151253  9-12
285  2022   0   4 -0.096509   1-4
286  2022   0   8  0.060656   5-8
287  2022   0  12 -0.025863  9-12
300  2023   0   4  0.138698   1-4
301  2023   0   8  0.034149   5-8
302  2023   0  12 -0.026050  9-12

In [41]:
array1 = group1_df[["加权回报率"]].to_numpy()

In [31]:
group2_df = df_filtered.loc[(df_filtered['分组'] == 1)] 
group2_df

年份  分组  季度     加权回报率    月份
168  2014   1   4  0.046654   1-4
169  2014   1   8  0.161585   5-8
170  2014   1  12  0.333220  9-12
183  2015   1   4  0.394389   1-4
184  2015   1   8  0.314187   5-8
185  2015   1  12  0.091305  9-12
198  2016   1   4 -0.155460   1-4
199  2016   1   8  0.034476   5-8
200  2016   1  12  0.080493  9-12
213  2017   1   4  0.025882   1-4
214  2017   1   8  0.050487   5-8
215  2017   1  12  0.075794  9-12
228  2018   1   4  0.018129   1-4
229  2018   1   8 -0.112809   5-8
230  2018   1  12 -0.145280  9-12
243  2019   1   4  0.375253   1-4
244  2019   1   8 -0.029929   5-8
245  2019   1  12  0.046458  9-12
258  2020   1   4 -0.021881   1-4
259  2020   1   8  0.350255   5-8
260  2020   1  12  0.074921  9-12
273  2021   1   4 -0.010913   1-4
274  2021   1   8  0.217727   5-8
275  2021   1  12  0.124878  9-12
288  2022   1   4 -0.141679   1-4
289  2022   1   8  0.093578   5-8
290  2022   1  12 -0.032139  9-12
303  2023   1   4  0.115312   1-4
304  2023   1   8 -0.018753   5-8
305  2023   1  12 -0.052222  9-12

In [29]:
array2 = group2_df[["加权回报率"]].to_numpy()
array2

array([[ 0.04665355],
       [ 0.16158539],
       [ 0.33322046],
       [ 0.3943891 ],
       [ 0.31418658],
       [ 0.09130511],
       [-0.15545992],
       [ 0.03447622],
       [ 0.080493  ],
       [ 0.02588174],
       [ 0.05048679],
       [ 0.07579374],
       [ 0.01812902],
       [-0.11280932],
       [-0.14527973],
       [ 0.37525291],
       [-0.02992875],
       [ 0.04645756],
       [-0.02188137],
       [ 0.35025524],
       [ 0.07492069],
       [-0.01091298],
       [ 0.21772683],
       [ 0.12487808],
       [-0.14167862],
       [ 0.09357828],
       [-0.03213918],
       [ 0.1153118 ],
       [-0.01875312],
       [-0.05222167]])

In [32]:
group3_df = df_filtered.loc[(df_filtered['分组'] == 2)] 
group3_df

年份  分组  季度     加权回报率    月份
171  2014   2   4  0.006625   1-4
172  2014   2   8  0.122769   5-8
173  2014   2  12  0.259555  9-12
186  2015   2   4  0.565399   1-4
187  2015   2   8  0.206630   5-8
188  2015   2  12  0.103564  9-12
201  2016   2   4 -0.138990   1-4
202  2016   2   8  0.071290   5-8
203  2016   2  12  0.098527  9-12
216  2017   2   4  0.006451   1-4
217  2017   2   8  0.019066   5-8
218  2017   2  12  0.059807  9-12
231  2018   2   4  0.026098   1-4
232  2018   2   8 -0.131392   5-8
233  2018   2  12 -0.115455  9-12
246  2019   2   4  0.371806   1-4
247  2019   2   8 -0.036853   5-8
248  2019   2  12  0.051781  9-12
261  2020   2   4  0.039900   1-4
262  2020   2   8  0.455902   5-8
263  2020   2  12  0.001258  9-12
276  2021   2   4 -0.040140   1-4
277  2021   2   8  0.154926   5-8
278  2021   2  12  0.159566  9-12
291  2022   2   4 -0.144128   1-4
292  2022   2   8  0.087989   5-8
293  2022   2  12 -0.006321  9-12
306  2023   2   4  0.063297   1-4
307  2023   2   8  0.029225   5-8
308  2023   2  12 -0.071463  9-12

In [34]:
array3 = group3_df[["加权回报率"]].to_numpy()
array3

array([[ 0.00662497],
       [ 0.12276931],
       [ 0.25955513],
       [ 0.56539852],
       [ 0.20663041],
       [ 0.10356394],
       [-0.13898962],
       [ 0.07129027],
       [ 0.09852653],
       [ 0.0064507 ],
       [ 0.01906597],
       [ 0.05980742],
       [ 0.02609808],
       [-0.13139199],
       [-0.11545532],
       [ 0.37180565],
       [-0.03685335],
       [ 0.05178081],
       [ 0.03989969],
       [ 0.45590248],
       [ 0.00125767],
       [-0.04013976],
       [ 0.15492557],
       [ 0.15956584],
       [-0.14412756],
       [ 0.08798905],
       [-0.00632149],
       [ 0.06329702],
       [ 0.02922505],
       [-0.0714631 ]])

In [35]:
group4_df = df_filtered.loc[(df_filtered['分组'] == 3)] 
group4_df

年份  分组  季度     加权回报率    月份
174  2014   3   4  0.054338   1-4
175  2014   3   8  0.187264   5-8
176  2014   3  12  0.330693  9-12
189  2015   3   4  0.520720   1-4
190  2015   3   8  0.217749   5-8
191  2015   3  12  0.165137  9-12
204  2016   3   4 -0.150868   1-4
205  2016   3   8  0.037910   5-8
206  2016   3  12  0.089341  9-12
219  2017   3   4 -0.003755   1-4
220  2017   3   8 -0.038222   5-8
221  2017   3  12  0.028361  9-12
234  2018   3   4  0.021679   1-4
235  2018   3   8 -0.116224   5-8
236  2018   3  12 -0.106395  9-12
249  2019   3   4  0.345592   1-4
250  2019   3   8 -0.035880   5-8
251  2019   3  12  0.083550  9-12
264  2020   3   4  0.061669   1-4
265  2020   3   8  0.497452   5-8
266  2020   3  12  0.044226  9-12
279  2021   3   4  0.026324   1-4
280  2021   3   8  0.213677   5-8
281  2021   3  12  0.168761  9-12
294  2022   3   4 -0.144719   1-4
295  2022   3   8  0.127991   5-8
296  2022   3  12 -0.051028  9-12
309  2023   3   4  0.085233   1-4
310  2023   3   8 -0.011386   5-8
311  2023   3  12 -0.044700  9-12

In [37]:
array4 = group4_df[["加权回报率"]].to_numpy()
array4

array([[ 0.05433769],
       [ 0.18726393],
       [ 0.3306927 ],
       [ 0.52071983],
       [ 0.21774866],
       [ 0.16513728],
       [-0.15086772],
       [ 0.03790994],
       [ 0.08934128],
       [-0.00375511],
       [-0.03822246],
       [ 0.02836075],
       [ 0.02167905],
       [-0.11622405],
       [-0.10639544],
       [ 0.34559223],
       [-0.03588037],
       [ 0.0835498 ],
       [ 0.06166869],
       [ 0.49745176],
       [ 0.04422585],
       [ 0.02632416],
       [ 0.21367663],
       [ 0.16876105],
       [-0.14471851],
       [ 0.12799066],
       [-0.0510282 ],
       [ 0.08523258],
       [-0.01138629],
       [-0.04470038]])

In [38]:
group5_df = df_filtered.loc[(df_filtered['分组'] == 4)] 
group5_df

年份  分组  季度     加权回报率    月份
177  2014   4   4  0.066765   1-4
178  2014   4   8  0.121851   5-8
179  2014   4  12  0.258102  9-12
192  2015   4   4  0.520878   1-4
193  2015   4   8  0.230071   5-8
194  2015   4  12  0.322903  9-12
207  2016   4   4 -0.131231   1-4
208  2016   4   8  0.059652   5-8
209  2016   4  12  0.116745  9-12
222  2017   4   4  0.043710   1-4
223  2017   4   8 -0.030481   5-8
224  2017   4  12  0.055501  9-12
237  2018   4   4  0.013485   1-4
238  2018   4   8 -0.063661   5-8
239  2018   4  12 -0.127318  9-12
252  2019   4   4  0.327305   1-4
253  2019   4   8 -0.007118   5-8
254  2019   4  12  0.087620  9-12
267  2020   4   4  0.053042   1-4
268  2020   4   8  0.468078   5-8
269  2020   4  12  0.102751  9-12
282  2021   4   4 -0.004663   1-4
283  2021   4   8  0.167632   5-8
284  2021   4  12  0.086051  9-12
297  2022   4   4 -0.165435   1-4
298  2022   4   8  0.131096   5-8
299  2022   4  12 -0.008302  9-12
312  2023   4   4  0.113041   1-4
313  2023   4   8  0.027757   5-8
314  2023   4  12 -0.077884  9-12

In [39]:
array5 = group5_df[["加权回报率"]].to_numpy()
array5

array([[ 0.06676516],
       [ 0.12185058],
       [ 0.25810192],
       [ 0.52087785],
       [ 0.23007061],
       [ 0.32290311],
       [-0.13123083],
       [ 0.05965187],
       [ 0.11674532],
       [ 0.04370988],
       [-0.03048137],
       [ 0.05550083],
       [ 0.01348517],
       [-0.0636614 ],
       [-0.12731833],
       [ 0.32730464],
       [-0.00711795],
       [ 0.08762013],
       [ 0.05304238],
       [ 0.46807769],
       [ 0.10275139],
       [-0.00466307],
       [ 0.16763233],
       [ 0.08605127],
       [-0.16543522],
       [ 0.13109581],
       [-0.00830162],
       [ 0.11304096],
       [ 0.02775683],
       [-0.07788414]])

In [44]:
# array5 - array1

array6 = array5 - array1
array6

array([[ 0.06332377],
       [-0.02832001],
       [-0.07592009],
       [ 0.09274899],
       [ 0.14888689],
       [ 0.20376723],
       [ 0.03770483],
       [ 0.02991055],
       [-0.03485247],
       [ 0.03644941],
       [-0.00986289],
       [-0.02113346],
       [ 0.02784379],
       [ 0.07844966],
       [-0.04777311],
       [-0.08140169],
       [ 0.05905148],
       [ 0.07072671],
       [ 0.04897591],
       [ 0.08955992],
       [ 0.11477309],
       [-0.013466  ],
       [-0.09242114],
       [-0.06520193],
       [-0.0689259 ],
       [ 0.07044022],
       [ 0.01756135],
       [-0.02565726],
       [-0.00639266],
       [-0.0518345 ]])

In [3]:

# 重新调整季度的映射
quarter_mapping = {
    4: '1-4',  # 代表第一季度
    8: '5-8',  # 代表第二季度
    12: '9-12'  # 代表第三季度
}

# 初始化结果存储
results = []




In [45]:

# # 分组和进行 t 检验
# for group in df_filtered['分组'].unique():
#     for year in range(2014, 2024):
#         for quarter_key, quarter_str in quarter_mapping.items():
#             # 对应年份和季度的数据
#             data = df[(df['分组'] == group) &
#                       (df['年份'] == year) &
#                       (df['季度'] == quarter_key)]
#             print(f"Checking group {group}, year {year}, quarter {quarter_str}: {len(data)} records found")

#             if not data.empty:
#                 print("data = ")
#                 print(data)
#                 t_stat, p_val = ttest_1samp(data, 0)
#                 print("t_stat = ")
#                 print(t_stat)
                
#                 results.append({
#                     '分组': group,
#                     '年份': year,
#                     '季度': quarter_str,
#                     't统计量': t_stat,
#                     'p值': p_val
#                 })

In [57]:
t_stat1, p_val1 = ttest_1samp(array1, 0)
print(t_stat1[0])
print(p_val1[0])

2.567032803148943
0.015681143651512883


In [47]:
t_stat2, p_val2 = ttest_1samp(array2, 0)
print(t_stat2[0])
print(p_val2[0])

In [48]:
t_stat3, p_val3 = ttest_1samp(array3, 0)
print(t_stat3[0])
print(p_val3[0])

In [49]:
t_stat4, p_val4 = ttest_1samp(array4, 0)
print(t_stat4[0])
print(p_val4[0])

In [50]:
t_stat5, p_val5 = ttest_1samp(array5, 0)
print(t_stat5[0])
print(p_val5[0])

In [51]:
t_stat6, p_val6 = ttest_1samp(array6, 0)
print(t_stat6[0])
print(p_val6[0])

In [ ]:

# 创建结果DataFrame
results_df = pd.DataFrame(results)
print(results_df)